config/routes.rb
  match "comment/moderate", :via => [:post, :get]
  match "comment/search", :via => [:post, :get]
  match "comment/show(.:format)(/:id)" => "comment#show", :via => [:post, :get]
  match "comment/destroy(.:format)(/:id)" => "comment#destroy", :via => [:post, :delete]
  match "comment/update(/:id)" => "comment#update", :via => [:post, :put]
  post "comment/create(.:format)"
  post "comment/mark_as_spam(/:id)" => "comment#mark_as_spam"

  # Dmail
  match "dmail(/inbox)" => "dmail#inbox", :via => [:post, :get]
  match "dmail/compose", :via => [:post, :get]
  get "dmail/preview"
  match "dmail/show(/:id)" => "dmail#show", :via => [:post, :get]
  match "dmail/show_previous_messages", :via => [:post, :get]
  post "dmail/create"
  get "dmail/mark_all_read" => "dmail#confirm_mark_all_read"
  post "dmail/mark_all_read"

  # Favorite
  match "favorite/list_users(.:format)", :via => [:post, :get]

  # Forum
  match "forum(/index)(.:format)" => "forum#index", :via => [:post, :get]
  match "forum/preview", :via => [:post, :get]
  match "forum/new", :via => [:post, :get]
  match "forum/add", :via => [:post, :get]
  match "forum/edit(/:id)" => "forum#edit", :via => [:post, :get]
  match "forum/show(/:id)" => "forum#show", :via => [:post, :get]
  match "forum/search", :via => [:post, :get]
  match "forum/mark_all_read", :via => [:post, :get]
  match "forum/lock", :via => [:post, :put]
  match "forum/stick(/:id)" => "forum#stick", :via => [:post, :put]
  match "forum/unlock(/:id)" => "forum#unlock", :via => [:post, :put]
  match "forum/unstick(/:id)" => "forum#unstick", :via => [:post, :put]
  match "forum/update(/:id)" => "forum#update", :via => [:post, :put]
  match "forum/destroy(/:id)" => "forum#destroy", :via => [:post, :delete]
  post "forum/create"

  # Help
  match "help(/index)" => "help#index", :via => [:post, :get]
  match "help/:action" => "help#:action", :via => [:post, :get]

  # History
  match "history(/index)" => "history#index", :via => [:post, :get]
  post "history/undo"

  # Inline
  match "inline(/index)" => "inline#index", :via => [:post, :get]
  match "inline/add_image(/:id)" => "inline#add_image", :via => [:post, :get]
  match "inline/create", :via => [:post, :get]
  match "inline/crop(/:id)" => "inline#crop", :via => [:post, :get]
  match "inline/edit(/:id)" => "inline#edit", :via => [:post, :get]
  match "inline/copy(/:id)" => "inline#copy", :via => [:post, :put]
  match "inline/update(/:id)" => "inline#update", :via => [:post, :put]
  match "inline/delete(/:id)" => "inline#delete", :via => [:post, :delete]
  match "inline/delete_image(/:id)" => "inline#delete_image", :via => [:post, :delete]

  # JobTask
  match "job_task(/index)" => "job_task#index", :via => [:post, :get]
  match "job_task/destroy(/:id)" => "job_task#destroy", :via => [:post, :get]
  match "job_task/restart(/:id)" => "job_task#restart", :via => [:post, :get]
  match "job_task/show(/:id)" => "job_task#show", :via => [:post, :get]

  # Note
  match "note(/index)(.:format)" => "note#index", :via => [:post, :get]
  match "note/history(.:format)(/:id)" => "note#history", :via => [:post, :get]
  match "note/search(.:format)", :via => [:post, :get]
  match "note/revert(.:format)(/:id)" => "note#revert", :via => [:post, :put]
  match "note/update(.:format)(/:id)" => "note#update", :via => [:post, :put]

  # Pool
  match "pool(/index)(.:format)" => "pool#index", :via => [:post, :get]
  match "pool/add_post(.:format)" => "pool#add_post", :via => [:post, :get]
  match "pool/copy(/:id)" => "pool#copy", :via => [:post, :get]
  match "pool/create(.:format)" => "pool#create", :via => [:post, :get]
  match "pool/destroy(.:format)(/:id)" => "pool#destroy", :via => [:post, :get]
  match "pool/import(/:id)" => "pool#import", :via => [:post, :get]
  match "pool/order(/:id)" => "pool#order", :via => [:post, :get]
  match "pool/remove_post(.:format)" => "pool#remove_post", :via => [:post, :get]
  match "pool/select", :via => [:post, :get]
  match "pool/show(.:format)(/:id)" => "pool#show", :via => [:post, :get]
  match "pool/transfer_metadata", :via => [:post, :get]
  match "pool/update(.:format)(/:id)" => "pool#update", :via => [:post, :get]
  match "pool/zip/:id/:filename" => "pool#zip", :constraints => { :filename => /.*/ }, :via => [:post, :get]

  # Post
  match "post(/index)(.:format)" => "post#index", :via => [:post, :get]
  match "post/acknowledge_new_deleted_posts", :via => [:post, :get]
  match "post/activate", :via => [:post, :get]
  match "post/atom(.:format)" => "post#atom", :defaults => { :format => :atom }, :via => [:post, :get]
  match "post/browse", :via => [:post, :get]
  match "post/delete(/:id)" => "post#delete", :via => [:post, :get]
  match "post/deleted_index", :via => [:post, :get]
  match "post/download", :via => [:post, :get]
  match "post/error", :via => [:post, :get]
  match "post/exception", :via => [:post, :get]
  match "post/histogram", :via => [:post, :get]
  match "post/moderate", :via => [:post, :get]
  match "post/piclens", :defaults => { :format => :rss }, :via => [:post, :get]
  match "post/popular_by_day", :via => [:post, :get]
  match "post/popular_by_month", :via => [:post, :get]
  match "post/popular_by_week", :via => [:post, :get]
  match "post/popular_recent", :via => [:post, :get]
  match "post/random(/:id)" => "post#random", :via => [:post, :get]
  match "post/show(/:id)(/*tag_title)" => "post#show", :constraints => { :id => /\d+/ }, :format => false, :via => [:post, :get]
  match "post/similar(/:id)" => "post#similar", :via => [:post, :get]
  match "post/undelete(/:id)" => "post#undelete", :via => [:post, :get]
  match "post/update_batch", :via => [:post, :get]
  match "post/upload", :via => [:post, :get]
  match "post/upload_problem", :via => [:post, :get]
  match "post/view(/:id)" => "post#view", :via => [:post, :get]
  match "post/flag(/:id)" => "post#flag", :via => [:post, :put]
  match "post/revert_tags(.:format)(/:id)" => "post#revert_tags", :via => [:post, :put]
  match "post/update(.:format)(/:id)" => "post#update", :via => [:post, :put]
  match "post/vote(.:format)(/:id)" => "post#vote", :via => [:post, :put]
  match "post/destroy(.:format)(/:id)" => "post#destroy", :via => [:post, :delete]
  post "post/create(.:format)" => "post#create"

  match "atom" => "post#atom", :defaults => { :format => :atom }, :via => [:post, :get]
  match "download" => "post#download", :via => [:post, :get]
  match "histogram" => "post#histogram", :via => [:post, :get]

  # PostTagHistory
  match "post_tag_history(/index)" => "post_tag_history#index", :via => [:post, :get]

  # Report
  match "report/tag_updates", :via => [:post, :get]
  match "report/note_updates", :via => [:post, :get]
  match "report/wiki_updates", :via => [:post, :get]
  match "report/post_uploads", :via => [:post, :get]
  match "report/votes", :via => [:post, :get]
  match "report/set_dates", :via => [:post, :get]

  # Settings
  namespace :settings do
    resource :api, :only => [:show, :update]
  end

  # Static
  match "static/500", :via => [:post, :get]
  match "static/more", :via => [:post, :get]
  match "static/terms_of_service", :via => [:post, :get]
  match "/opensearch" => "static#opensearch", :via => [:post, :get]

  # TagAlias
  match "tag_alias(/index)" => "tag_alias#index", :via => [:post, :get]
  match "tag_alias/update", :via => [:post, :put]
  post "tag_alias/create"

  # Tag
  match "tag(/index)(.:format)" => "tag#index", :via => [:post, :get]
  get "tag/autocomplete_name", :as => :ac_tag_name
  match "tag/cloud", :via => [:post, :get]
  match "tag/edit(/:id)" => "tag#edit", :via => [:post, :get]
  match "tag/edit_preview", :via => [:post, :get]
  match "tag/mass_edit", :via => [:post, :get]
  match "tag/popular_by_day", :via => [:post, :get]
  match "tag/popular_by_month", :via => [:post, :get]
  match "tag/popular_by_week", :via => [:post, :get]
  match "tag/related(.:format)" => "tag#related", :via => [:post, :get]
  match "tag/show(/:id)" => "tag#show", :via => [:post, :get]
  match "tag/summary", :via => [:post, :get]
  match "tag/update(.:format)" => "tag#update", :via => [:post, :get]

  # TagImplication
  match "tag_implication(/index)" => "tag_implication#index", :via => [:post, :get]
  match "tag_implication/update", :via => [:post, :put]
  post "tag_implication/create"

  # TagSubscription
  match "tag_subscription(/index)" => "tag_subscription#index", :via => [:post, :get]
  match "tag_subscription/create", :via => [:post, :get]
  match "tag_subscription/update", :via => [:post, :get]
  match "tag_subscription/destroy(/:id)" => "tag_subscription#destroy", :via => [:post, :get]

  # User
  get "user/autocomplete_name", :as => :ac_user_name
  match "user(/index)(.:format)" => "user#index", :via => [:post, :get]
  match "user/activate_user", :via => [:post, :get]
  match "user/block(/:id)" => "user#block", :via => [:post, :get]
  match "user/change_email", :via => [:post, :get]
  match "user/change_password", :via => [:post, :get]
  match "user/check", :via => [:post, :get]
  match "user/edit", :via => [:post, :get]
  match "user/error", :via => [:post, :get]
  match "user/home", :via => [:post, :get]
  match "user/invites", :via => [:post, :get]
  match "user/login", :via => [:post, :get]
  match "user/logout", :via => [:post, :get]
  match "user/remove_from_blacklist", :via => [:post, :get]
  match "user/resend_confirmation", :via => [:post, :get]
  match "user/reset_password", :via => [:post, :get]
  match "user/set_avatar(/:id)" => "user#set_avatar", :via => [:post, :get]
  match "user/show(/:id)" => "user#show", :via => [:post, :get]
  match "user/show_blocked_users", :via => [:post, :get]
  match "user/signup", :via => [:post, :get]
  match "user/unblock", :via => [:post, :get]
  match "user/authenticate", :via => [:post, :put]
  match "user/modify_blacklist", :via => [:post, :put]
  match "user/update", :via => [:post, :put, :patch]
  post "user/create"
  post "user/remove_avatar/:id" => "user#remove_avatar"

app/helpers/pool_helper.rb
module PoolHelper
  def pool_list(post)
    html = ""
    pools = Pool.find(:all, :joins => "JOIN pools_posts ON pools_posts.pool_id = pools.id", :conditions => "pools_posts.post_id = #{post.id}", :order => "pools.name", :select => "pools.name, pools.id")

    if pools.empty?
      html << "none"
    else
      html << pools.map { |p| link_to(h(p.pretty_name), :controller => "pool", :action => "show", :id => p.id) }.join(", ")
    end

    html
  end

  def link_to_pool_zip(text, pool, zip_params, options = {})
    text = "%s%s (%s)" % [text,
                          options[:has_jpeg] ? " PNGs" : "",
                          number_to_human_size(pool.get_zip_size(zip_params).to_i)
                         ]
    options = { :action => "zip", :id => pool.id, :filename => pool.get_zip_filename(zip_params) }
    options[:jpeg] = 1 if zip_params[:jpeg]
    link_to text, options, :level => :member
  end

  def generate_zip_list
    unless @pool_zip.blank?
      @pool_zip.map do |data|
        "%s %s %s %s\n" % [data[:crc32], data[:file_size], data[:path], data[:filename]]
      end.join
    end
  end
end

app/views/pool/_import_list.html.erb
<%
  fields = ''.html_safe
  thumbnails = ''.html_safe
  @posts.each_with_index do |p, i|
    fields << hidden_field_tag("posts[#{p.id}]", "%05i" % i)
    thumbnails << print_preview(p, :onclick => "return removePost(#{p.id})")
  end
%>
<div style="margin-bottom: 2em;">
  <%= check_box_tag("delete-mode") %>
  <%= content_tag(:label, "Remove posts", :onclick => "Element.toggle('delete-mode-help')", :for => "delete-mode") %>
  <%= content_tag(:p, content_tag(:em, "When delete mode is enabled, clicking on a thumbnail will remove that post from the import."), :style => "display: none;", :id => "delete-mode-help") %>
</div>
<%= fields %>
<%= thumbnails %>

app/views/pool/_pool_atom.html.erb
<%= link_to image_tag(URI.join(root_url(:only_path => false), sample.preview_url), :title => pool.pretty_name), pool_url %>

app/views/pool/_select_form.html.erb
<%= form_tag(:action => "add_post") do %>
  <%= hidden_field_tag "post_id", params[:post_id] %>
  <%= select_tag "pool_id", options_for_select(@pools.map {|x| [x.name.tr("_", " "), x.id]}, session[:last_pool_id]) %>
  <%= button_to_function t('.add'), "Pool.add_post(#{@post_id}, $F('pool_id'))", :level => :member %>
<% end %>

app/views/pool/add_post.html.erb
<% provide :title, t('.title') %>
<h3><%= t('.title') %></h3>

<%= link_to(image_tag(@post.preview_url), :controller => "post", :action => "show", :id => @post.id) %>

<p><%= t('.info') %></p>

<%= form_tag(:action => "add_post") do %>
  <%= hidden_field_tag("post_id", @post.id) %>

  <table>
    <tbody>
      <tr>
        <th width="15%"><label for="pool_name"><%= t('.pool') %></label></th>
        <td width="85%">
          <select name="pool_id">
            <%= options_from_collection_for_select @pools, :id, :pretty_name %>
          </select>
      </tr>
      <tr>
        <th><label for="pool_sequence"><%= t('.order') %></label></th>
        <td><%= text_field "pool", "sequence", :size => 5, :value => "" %></td>
      </tr>
    </tbody>
  </table>

  <%= submit_tag t('.add') %> <%= button_to_function t('.cancel'), "history.back()" %>
<% end %>

<%= render :partial => "footer" %>

app/views/pool/copy.html.erb
<% provide :title, t('.title') %>
<h4><%= t('.title') %></h4>

<%= form_tag(:action => "copy") do %>
  <%= hidden_field_tag "id", params[:id] %>
  <label><%= t('.name') %></label> <%= text_field_tag "name", @new_pool.pretty_name %>
  <%= submit_tag t('.copy') %> <%= button_to_function t('buttons.cancel'), "history.back()" %></td>
<% end %>

<%= render :partial => "footer" %>

<script type="text/javascript">$("name").focus();</script>

app/views/pool/destroy.html.erb
<% provide :title, t('.title') %>
<h3><%= t('.title') %></h3>

<%= form_tag(:action => "destroy") do %>
  <p><%= t('.confirm', :name => @pool.pretty_name) %></p>
  <%= submit_tag t('buttons._yes') %> <%= button_to_function t('buttons._no'), "history.back()" %>
<% end %>

<%= render :partial => "footer" %>

app/views/pool/import.js.erb
Element.update('posts', '<%= escape_javascript render('import_list') %>');

app/views/pool/index.html.erb
<% provide :title, params[:query] ? t('.title', :q => params[:query]) : t('.title_main') %>
<div id="pool-index">
  <div style="margin-bottom: 2em;">
    <%= form_tag({:action => "index"}, :method => :get) do %>
      <% if params.has_key?(:order) %>
      <%= hidden_field_tag "order", params[:order] %>
      <% end %>
      <%= text_field_tag "query", params[:query], :size => 40 %>
      <%= submit_tag t('.search') %>
    <% end %>
  </div>

  <%= image_tag 'blank.gif', :id => 'hover-thumb', :alt => '', :style => 'position: absolute; display: none; border: 2px solid #000; right: 42%;' %>

  <table width="100%" class="highlightable">
    <thead>
      <tr>
        <th width="60%"><%= t('.table.name') %></th>
        <th width="*"><%= t('.table.creator') %></th>
        <th width="*"><%= t('.table.posts') %></th>
        <th width="*"><%= t('.table.created') %></th>
        <th width="*"><%= t('.table.updated') %></th>
      </tr>
    </thead>
    <tbody>
      <% @pools.each do |p| %>
        <tr class="<%= cycle 'even', 'odd' %>" id="p<%= p.id %>">
          <td><%= link_to h(p.pretty_name), :action => "show", :id => p.id %></td>
          <td><%= h(p.user.pretty_name) %></td>
          <td><%= p.post_count %></td>
          <td><%= t('time.x_ago', :t => time_ago_in_words(p.created_at)) %></td>
          <td><%= t('time.x_ago', :t => time_ago_in_words(p.updated_at)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="paginator">
  <%= will_paginate(@pools) %>
</div>

<% content_for :post_cookie_javascripts do %>
<script type="text/javascript">
  var thumb = $("hover-thumb");
  <% @samples.each do |pool, post| %>
    Post.register(<%= json_escape post.to_json.html_safe %>);
    var hover_row = $("p<%= pool.id %>");
    var container = hover_row.up("TABLE");
    Post.init_hover_thumb(hover_row, <%= post.id %>, thumb, container);
  <% end %>
  Post.init_blacklisted({replace: true});

  <% @samples.each do |pool, post| %>
    if(!Post.is_blacklisted(<%= post.id %>))
      Preload.preload('<%= escape_javascript(post.preview_url) %>');
  <% end %>
</script>
<% end %>

<%= render :partial => "footer" %>

app/views/pool/order.html.erb
<h3><%= t('.title_html', :name => link_to(@pool.pretty_name, :action => :show, :id => @pool.id)) %></h3>
<p><%= t('.info') %></p>

<script type="text/javascript">
  function orderAutoFill() {
    var i = 0
    var step = parseInt(prompt('<%= t('.interval') %>'))

    $$(".pp").each(function(x) {
      x.value = i
      i += step
    })
  }

  function orderReverse() {
    var orders = []
    $$(".pp").each(function(x) {
      orders.push(x.value)
    })
    var i = orders.size() - 1
    $$(".pp").each(function(x) {
      x.value = orders[i]
      i -= 1
    })
  }

  function orderShift(start, offset) {
    var found = false;
    $$(".pp").each(function(x) {
      if(x.id == "pool_post_sequence_" + start)
        found = true;
      if(!found)
        return;
      x.value = Number(x.value) + offset;
    });
  }
</script>

<%= form_tag(:action => "order") do %>
  <%= hidden_field_tag "id", @pool.id %>
  <table>
    <thead>
      <tr>
        <th></th>
        <th><%= t('.order') %></th>
      </tr>
    </thead>
    <tbody>
      <% @pool_posts.each do |pp| %>
        <tr>
          <td>
            <% if pp.post.can_be_seen_by?(@current_user) %>
              <%= link_to(image_tag(pp.post.preview_url, :width => pp.post.preview_dimensions[0], :height => pp.post.preview_dimensions[1]), {:controller => "post", :action => "show", :id => pp.post_id}, :title => pp.post.cached_tags)%>
            <% end %>
          </td>
          <td>
            <%= text_field_tag "pool_post_sequence[#{pp.id}]", pp.sequence, :class => "pp", :size => 5, :tabindex => 1 %>
            <%= link_to_function t('.plus_one'), "orderShift(#{pp.id}, +1)", :class=>"text-button" %>
            <%= link_to_function t('.minus_one'), "orderShift(#{pp.id}, -1)", :class=>"text-button" %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"><%= submit_tag t('buttons.save'), :tabindex => 2 %> <%= button_to_function t('.auto_order'), "orderAutoFill()", :tabindex => 2 %> <%= button_to_function t('.reverse'), "orderReverse()", :tabindex => 2 %> <%= button_to_function t('buttons.cancel'), "history.back()", :tabindex => 2 %></td>
      </tr>
    </tfoot>
  </table>
<% end %>

app/views/pool/select.html.erb
<%= render :partial => 'select_form' %>

app/views/pool/select.js.erb
$('add-to-pool').update('<%= escape_javascript render(:partial => 'select_form') %>');

app/views/pool/transfer_metadata.html.erb
<% if @from.nil? then %>
  <%= form_tag({:controller => "pool", :action => "transfer_metadata"}, :method => "get") do %>
  <%= hidden_field_tag t('.from.to'), @to.id %>
  <%= t('.from.from_number') %>
  <%= text_field_tag t('.from.from'), "", :class => "fp", :size => 5, :tabindex => 1 %>
  <br>
  <%= submit_tag t('.from.transfer'), :tabindex => 2 %>
  <%= button_to_function t('buttons.cancel'), "history.back()", :tabindex => 2 %>
  <script type="text/javascript">$("from").focus()</script>
<% end %>

<% else %>
<h3>
  <%=
    t('.title_html',
      :from => link_to(@from.pretty_name, :action => :show, :id => @from.id),
      :to => link_to(@to.pretty_name, :action => :show, :id => @to.id))
  %>
</h3>

<div>
  <%= t('.info_what') %>
</div>
<% if @truncated then %>
<div>
 <%= t('.info_truncated') %>
 <b><%= t('.info_truncated_warning') %></b>
</div>
<% end %>

<div><%= t('.reverse_text_html', :reverse => link_to(t('.reverse'), { :action => "transfer_metadata", :from => @to.id, :to => @from.id})) %></div>

<%= form_tag(:controller => "post", :action => "update_batch") do %>
<%= hidden_field_tag "url", (url_for :controller => "pool", :action => "show", :id => @to.id) %>
  <table>
    <thead>
      <tr>
        <th><%= t('.table.from') %></th>
        <th><%= t('.table.to') %></th>
        <th><%= t('.table.tags') %></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |pp| %>
        <% fp = pp[:from]; tp = pp[:to] %>
        <tr>
          <td>
            <% if fp.can_be_seen_by?(@current_user) %>
              <%= link_to(image_tag(fp.preview_url, :width => fp.preview_dimensions[0], :height => fp.preview_dimensions[1]), {:controller => "post", :action => "show", :id => fp.id}, :title => fp.cached_tags)%>
            <% end %>
          </td>
          <td>
            <% if tp.can_be_seen_by?(@current_user) %>
              <%= link_to(image_tag(tp.preview_url, :width => tp.preview_dimensions[0], :height => tp.preview_dimensions[1]), {:controller => "post", :action => "show", :id => tp.id}, :title => tp.cached_tags)%>
            <% end %>
          </td>
          <td>
            <%= hidden_field_tag "post[#{tp.id}][old_tags]", tp.tags %>
            <%= text_field_tag "post[#{tp.id}][tags]", pp[:tags], :class => "fp", :size => 45, :tabindex => 1 %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"><%= submit_tag t('.table.transfer'), :tabindex => 2 %> <%= button_to_function t('buttons.cancel'), "history.back()", :tabindex => 2 %></td>
      </tr>
    </tfoot>
  </table>
<% end %>
<% end %>

app/views/pool/update.html.erb
<h3><%= t('.title') %></h3>

<%= form_tag(:action => "update") do %>
  <table class="form">
    <tbody>
      <tr>
        <th width="15%"><label for="pool_name"><%= t('.form.name') %></label></th>
        <td width="85%"><%= text_field "pool", "name", :value => @pool.pretty_name %></td>
      </tr>
      <tr>
        <th><label for="pool_description"><%= t('.form.description') %></label></th>
        <td><%= text_area "pool", "description", :size => "40x10" %></td>
      </tr>
      <tr>
        <th>
          <label for="pool_is_public"><%= t('.form.is_public._') %></label>
          <p><%= t('.form.is_public.info') %></p>
        </th>
        <td><%= check_box "pool", "is_public" %></td>
      </tr>
      <tr>
        <th>
          <label for="pool_is_active"><%= t('.form.is_active._') %></label>
          <p><%= t('.form.is_active.info') %></p>
        </th>
        <td><%= check_box "pool", "is_active" %></td>
      </tr>
      <tr>
        <td colspan="2"><%= submit_tag t('buttons.save') %> <%= button_to_function t('buttons.cancel'), "history.back()" %></td>
      </tr>
    </tbody>
  </table>
<% end %>

<%= render :partial => "footer" %>

app/views/pool/zip.html.erb
<%= generate_zip_list -%>